name: Build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SOURCE_DATE_EPOCH: 1640995200
    steps:
      - uses: actions/checkout@v3
      - name: Install
        run: sudo apt-get install -y texlive-latex-recommended texlive-fonts-recommended texlive-fonts-extra texlive-latex-extra texlive-science texlive-bibtex-extra lmodern
      - name: Build
        run: |
          cd euroscipy-2017 && pdflatex -halt-on-error euroscipy-2017.tex && pdflatex euroscipy-2017.tex && cd -
          cd lowranktensor && pdflatex -halt-on-error lowranktensor.tex && pdflatex lowranktensor.tex && cd -
          for subdir in agenda overview architecture uncertainties library_development module_development doc_development tps; do cd developer/${subdir} && pdflatex -halt-on-error ${subdir}.tex && pdflatex ${subdir}.tex && cd -; done
          cd uncecomp2017/Uncecomp2017-article-OT && pdflatex -halt-on-error uncecomp-2017-article-OpenTURNS.tex && bibtex uncecomp-2017-article-OpenTURNS && pdflatex uncecomp-2017-article-OpenTURNS.tex && pdflatex uncecomp-2017-article-OpenTURNS.tex && cd -
          cd uncecomp2017/Uncecomp2017-slides-OT && pdflatex -halt-on-error uncecomp-2017-slides-OpenTURNS.tex && pdflatex uncecomp-2017-slides-OpenTURNS.tex && cd -
          cd uncecomp2019/Uncecomp2019-article-OT && pdflatex -halt-on-error uncecomp-2019-article-OpenTURNS.tex && bibtex uncecomp-2019-article-OpenTURNS && pdflatex uncecomp-2019-article-OpenTURNS.tex && pdflatex uncecomp-2019-article-OpenTURNS.tex && cd -
          cd uncecomp2019/Uncecomp2019-slides-OT && pdflatex -halt-on-error uncecomp-2019-slides-OpenTURNS.tex && pdflatex uncecomp-2019-slides-OpenTURNS.tex && cd -
          cd chorus-2017-otfmi && pdflatex -halt-on-error chorus-2017-otfmi.tex && pdflatex chorus-2017-otfmi.tex && cd -
          cd siamuq2020 && pdflatex -halt-on-error siamuq-2020-slides-OpenTURNS.tex && pdflatex siamuq-2020-slides-OpenTURNS.tex && cd -
          cd siamuq2022 && pdflatex -halt-on-error siamuq-2022-slides-OpenTURNS.tex && pdflatex siamuq-2022-slides-OpenTURNS.tex && cd -
          cd applibugs2023 && pdflatex -halt-on-error applibugs-2023-slides_OpenTURNS_MetropolisHastings.tex && pdflatex applibugs-2023-slides_OpenTURNS_MetropolisHastings.tex && cd -
          cd userday2020/userday2020relhi/ && pdflatex -halt-on-error userday2020relhi.tex && pdflatex userday2020relhi.tex && cd -
          cd userday2020/ud2020persalys && pdflatex -halt-on-error UsersDay-2020-PERSALYS.tex && pdflatex UsersDay-2020-PERSALYS.tex && cd -
          cd userday2021/userday2021relhi/ && pdflatex -halt-on-error userday2021relhi.tex && pdflatex userday2021relhi.tex && cd -
          cd userday2021/frasil_EDF_OTUsers2021 && bash build-slides.sh && cd -
          cd userday2022/functional_sensitivity && pdflatex -halt-on-error functional_sensitivity.tex && pdflatex functional_sensitivity.tex && cd -
          cd userday2022/userday2022relhi/ && pdflatex -halt-on-error userday2022relhi.tex && pdflatex userday2022relhi.tex && cd -
          cd userday2022/ud2022persalys && pdflatex -halt-on-error UsersDay-2022-PERSALYS.tex && pdflatex UsersDay-2022-PERSALYS.tex && cd -
      - name: Upload
        if: ${{ github.ref == 'refs/heads/master' }}
        run: |
          git clone --depth 1 https://${{ secrets.GH_TOKEN }}@github.com/openturns/openturns.github.io.git /tmp/io
          mkdir -p /tmp/io/presentation/master
          rm -r developer/tps/annex
          find . -name "*.pdf" | grep -v figure | xargs -I{} cp -v {} /tmp/io/presentation/master
          cd /tmp/io
          touch .nojekyll
          git config user.email "support@gh.com"
          git config user.name "GitHub Actions"
          git add -A .
          if test `git diff HEAD | wc -c` -eq 0; then exit 0; fi
          git commit -a -m "GitHub Actions build ${GITHUB_REPOSITORY} ${GITHUB_RUN_ID}"
          git push --quiet origin master > /dev/null 2>&1
